<a href="https://colab.research.google.com/github/Anshikap099/py-python/blob/main/Sales_Forecasting_Dashboard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**📊 Sales Forecasting using Machine Learning**

### Name: Anshika Pandey
### Roll no. : 25SCS1003002561
### Project: Data Science Project  
### Tool: Google Colab# New Section

**1. Setup**

In [ ]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.display import display, HTML, clear_output
import time

**2. Load Dataset**

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1NI1A7GZfFPKfQmLyYm_xknCTuKGF0fz_/export?format=csv"
df = pd.read_csv(url)

df.columns = df.columns.str.lower()
df.head()

,row id+o6g3a1:r6,order id,order date,ship date,ship mode,customer id,customer name,segment,country,city,...,category,sub-category,product name,sales,quantity,profit,returns,payment mode,ind1,ind2
0,4918,CA-2019-160304,1/1/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,1/2/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,1/2/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,1/3/2019,1/5/2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,1/3/2019,1/8/2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

**3. Data Cleaning + Feature Engineering**

In [ ]:
df = df.drop(columns=['ind1', 'ind2'], errors='ignore')
df['returns'] = df['returns'].fillna(0)

df['date'] = pd.to_datetime(df['order date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

**4. FILTER SYSTEM**

In [ ]:
region_selected = "All"  # change to Central/East/West if needed

if region_selected != "All":
    df = df[df['region'] == region_selected]

**5. KPI CARDS**

In [ ]:
if not df.empty:
    total_sales = int(df['sales'].sum())
    orders = len(df)
    avg_sales = int(df['sales'].mean())
    profit = int(total_sales * 0.1)
else:
    total_sales = 0
    orders = 0
    avg_sales = 0
    profit = 0

display(HTML(f"""
<div style='display:flex; gap:20px;'>
  <div style='background:#1f2c3c; padding:20px; border-radius:12px; color:white'>
    <h4>Orders</h4><h2>{orders}</h2>
  </div>
  <div style='background:#1f2c3c; padding:20px; border-radius:12px; color:white'>
    <h4>Sales</h4><h2>{total_sales}</h2>
  </div>
  <div style='background:#1f2c3c; padding:20px; border-radius:12px; color:white'>
    <h4>Profit</h4><h2>{profit}</h2>
  </div>
  <div style='background:#1f2c3c; padding:20px; border-radius:12px; color:white'>
    <h4>Avg Sales</h4><h2>{avg_sales}</h2>
  </div>
</div>
"""))

**6. PREPARE DATA**

In [ ]:
monthly = df.groupby(['year','month'])['sales'].sum().reset_index()
category = df.groupby('category')['sales'].sum().reset_index()
region = df.groupby('region')['sales'].sum().reset_index()

**7. ANIMATED CHARTS**

In [ ]:
df['year'].unique()

array([2019, 2020], dtype=int32)

In [ ]:
fig = px.line(
    monthly,
    x='month',
    y='sales',
    markers=True,
    title="📈 Sales Trend"
)
fig.update_layout(template="plotly_dark")
fig.show()

**Category Animation**

In [ ]:
cat_year = df.groupby(['year','category'])['sales'].sum().reset_index()

fig2 = px.bar(
    cat_year, x='category', y='sales',
    color='category',
    animation_frame='year'
)
fig2.update_layout(template="plotly_dark")
fig2.show()

In [ ]:
monthly['frame'] = monthly['month']

fig = px.line(
    monthly,
    x='month',
    y='sales',
    animation_frame='frame',
    markers=True,
    title="📈 Sales Trend"
)
fig.update_layout(template="plotly_dark")
fig.show()

NameError: name 'monthly' is not defined

**Region Pie Animation**

In [ ]:
region_year = df.groupby(['year','region'])['sales'].sum().reset_index()

fig3 = px.bar(
    region_year,
    x='region',
    y='sales',
    color='region',
    animation_frame='year',
    title="📈 Regional Sales Trend Animation (Bar Chart)"
)
fig3.update_layout(template="plotly_dark")
fig3.show()

In [ ]:
if not region.empty:
    fig_static_pie = px.pie(
        region,
        names='region',
        values='sales',
        title="Overall Regional Sales Distribution"
    )
    fig_static_pie.update_layout(template="plotly_dark")
    fig_static_pie.show()
else:
    print("The 'region' DataFrame is empty. Please check previous data processing steps.")

In [ ]:
cat_year = df.groupby(['category'], as_index=False)['sales'].sum()

fig = px.bar(
    cat_year,
    x='category',
    y='sales',
    color='category',
    title="📊 Category Sales"
)
fig.update_layout(template="plotly_dark")
fig.show()

In [ ]:
print(df.columns)
print(df.head())
print(df['year'].unique())

Index(['row id+o6g3a1:r6', 'order id', 'order date', 'ship date', 'ship mode',
       'customer id', 'customer name', 'segment', 'country', 'city', 'state',
       'region', 'product id', 'category', 'sub-category', 'product name',
       'sales', 'quantity', 'profit', 'returns', 'payment mode', 'date',
       'year', 'month'],
      dtype='object')
   row id+o6g3a1:r6        order id order date ship date       ship mode  \
0              4918  CA-2019-160304   1/1/2019  1/7/2019  Standard Class
1              4919  CA-2019-160304   1/2/2019  1/7/2019  Standard Class
2              4920  CA-2019-160304   1/2/2019  1/7/2019  Standard Class
3              3074  CA-2019-125206   1/3/2019  1/5/2019     First Class
4              8604  US-2019-116365   1/3/2019  1/8/2019  Standard Class

  customer id      customer name    segment        country          city  ...  \
0    BM-11575      Brendan Murry  Corporate  United States  Gaithersburg  ...
1    BM-11575      Brendan Murry  Corporate  United States  Gaithersburg  ...
2    BM-11575      Brendan Murry  Corporate  United States  Gaithersburg  ...
3    LR-16915       Lena Radford   Consumer  United States   Los Angeles  ...
4    CA-12310  Christine Abelman  Corporate  United States   San Antonio  ...

  sub-category                                       product name   sales  \
0    Bookcases  Bush Westfield Collection Bookcases, Medium Ch...   73.94
1    Bookcases  Bush Westfield Collection Bookcases, Medium Ch...  173.94
2       Phones                                        GE 30522EE2  231.98
3      Storage  Recycled Steel Personal File for Hanging File ...  114.46
4  Accessories                Imation Clip USB flash drive - 8 GB   30.08

  quantity   profit returns  payment mode       date  year  month
0        1  28.2668     0.0        Online 2019-01-01  2019      1
1        3  38.2668     0.0        Online 2019-01-02  2019      1
2        2  67.2742     0.0         Cards 2019-01-02  2019      1
3        2  28.6150     0.0        Online 2019-01-03  2019      1
4        2  -5.2640     0.0        Online 2019-01-03  2019      1

[5 rows x 24 columns]
[2019 2020]

**8. MACHINE LEARNING MODEL**

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1NI1A7GZfFPKfQmLyYm_xknCTuKGF0fz_/export?format=csv"
df = pd.read_csv(url)

df.columns = df.columns.str.lower()
print("DataFrame reloaded. First 5 rows:")
display(df.head())

DataFrame reloaded. First 5 rows:

,row id+o6g3a1:r6,order id,order date,ship date,ship mode,customer id,customer name,segment,country,city,...,category,sub-category,product name,sales,quantity,profit,returns,payment mode,ind1,ind2
0,4918,CA-2019-160304,1/1/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,1/2/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,1/2/2019,1/7/2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,1/3/2019,1/5/2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,1/3/2019,1/8/2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

In [ ]:
df = df.drop(columns=['ind1', 'ind2'], errors='ignore')
df['returns'] = df['returns'].fillna(0)

df['date'] = pd.to_datetime(df['order date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
print("Data cleaning and feature engineering re-applied.")
print(f"DataFrame shape after cleaning: {df.shape}")

Data cleaning and feature engineering re-applied.
DataFrame shape after cleaning: (5901, 24)

In [ ]:
region_selected = "All"  # change to Central/East/West if needed

if region_selected != "All":
    df = df[df['region'] == region_selected]
print(f"Region filter re-applied. Current region selection: {region_selected}")
print(f"DataFrame shape after filtering: {df.shape}")

Region filter re-applied. Current region selection: All
DataFrame shape after filtering: (5901, 24)

In [ ]:
monthly = df.groupby(['year','month'])['sales'].sum().reset_index()
category = df.groupby('category')['sales'].sum().reset_index()
region = df.groupby('region')['sales'].sum().reset_index()
print("Aggregated DataFrames (monthly, category, region) re-prepared.")

Aggregated DataFrames (monthly, category, region) re-prepared.

In [ ]:
from sklearn.ensemble import RandomForestRegressor

X = df[['year','month']]
y = df['sales']

model = RandomForestRegressor()
model.fit(X,y)

RandomForestRegressor()

In [ ]:
future_years = [2021] * 12
future_months = range(1, 13)
forecast_input = pd.DataFrame({
    'year': future_years,
    'month': future_months
})
print("Forecast input data created for the next 12 months.")
display(forecast_input.head())

Forecast input data created for the next 12 months.

   year  month
0  2021      1
1  2021      2
2  2021      3
3  2021      4
4  2021      5

In [ ]:
forecast = model.predict(forecast_input)
print("Sales forecast generated using the trained model.")

Sales forecast generated using the trained model.

**9. FORECAST**

In [ ]:
forecast_df = pd.DataFrame({
    'Month': range(1, 13),
    'Predicted Sales': forecast
})
print("Forecast DataFrame created.")
display(forecast_df.head())

Forecast DataFrame created.

   Month  Predicted Sales
0      1       344.815727
1      2       486.379866
2      3       266.983182
3      4       246.800852
4      5       277.631692

In [ ]:
import pandas as pd

frames = []

for i in range(1, 13):
    temp = forecast_df.iloc[:i].copy()
    temp['frame'] = i
    frames.append(temp)

animated_df = pd.concat(frames)

In [ ]:
import plotly.express as px

fig = px.line(
    animated_df,
    x='Month',
    y='Predicted Sales',
    animation_frame='frame',
    markers=True,
    title="🔮 Animated Sales Forecast"
)

fig.update_layout(
    template="plotly_dark",
    transition={'duration': 500}
)

fig.show()

**10. FINAL DASHBOARD**

In [ ]:
dashboard = make_subplots(
    rows=2, cols=2,
    subplot_titles=("Monthly", "Category", "Region", "Forecast"),
    specs=[[{"type":"scatter"},{"type":"bar"}],
           [{"type":"pie"},{"type":"scatter"}]]
)

dashboard.add_trace(go.Scatter(x=monthly['month'], y=monthly['sales']),1,1)
dashboard.add_trace(go.Bar(x=category['category'], y=category['sales']),1,2)
dashboard.add_trace(go.Pie(labels=region['region'], values=region['sales']),2,1)
dashboard.add_trace(go.Scatter(x=forecast_df['Month'], y=forecast_df['Predicted Sales']),2,2)

dashboard.update_layout(
    height=700,
    template="plotly_dark",
    title="🔥 Final Sales Dashboard"
)

dashboard.show()

**11. AUTO INSIGHTS**

In [ ]:
insights = []

if df['sales'].mean() > 500:
    insights.append("Sales are generally strong.")

if df.groupby('month')['sales'].sum().idxmax() == 12:
    insights.append("December has peak sales.")

if len(region) > 0:
    top_region = region.sort_values(by='sales', ascending=False).iloc[0]['region']
    insights.append(f"Top performing region is {top_region}.")

display(HTML(f"""
<div style='background:#1f2c3c; padding:20px; border-radius:12px; color:white'>
<h3>📊 AI Insights</h3>
<ul>
{''.join([f"<li>{i}</li>" for i in insights])}
</ul>
</div>
"""))

**GENERATE SMART INSIGHTS**

In [ ]:
insights = []

# 📈 Trend Insight
monthly_sales = df.groupby('month')['sales'].sum()
trend = "increasing" if monthly_sales.iloc[-1] > monthly_sales.iloc[0] else "fluctuating"
insights.append(f"Sales trend is overall {trend} throughout the year.")

# 🏆 Top Category
if 'category' in df.columns:
    top_cat = df.groupby('category')['sales'].sum().idxmax()
    insights.append(f"Top performing category is {top_cat}.")

# 🌍 Top Region
if 'region' in df.columns:
    top_region = df.groupby('region')['sales'].sum().idxmax()
    insights.append(f"Highest sales come from {top_region} region.")

# 🔮 Forecast Insight
if forecast_df['Predicted Sales'].iloc[-1] > forecast_df['Predicted Sales'].iloc[0]:
    insights.append("Forecast indicates a growth trend in upcoming months.")
else:
    insights.append("Forecast indicates a potential decline or fluctuation.")

# 📊 Peak Month
peak_month = monthly_sales.idxmax()
insights.append(f"Sales peak observed in month {peak_month}.")

**PROFESSIONAL DISPLAY**

In [ ]:
from IPython.display import display, HTML

display(HTML(f"""
<div style='background:#1f2c3c; padding:25px; border-radius:15px; color:white; margin-top:20px'>
<h2>🤖 AI-Powered Business Insights</h2>

<div style='display:flex; gap:20px'>

<div style='flex:2'>
<ul style='line-height:1.8; font-size:16px'>
{''.join([f"<li>📌 {i}</li>" for i in insights])}
</ul>
</div>

<div style='flex:1; background:#26374d; padding:15px; border-radius:10px'>
<h4>📊 Summary</h4>
<p><b>Total Sales:</b> {int(df['sales'].sum())}</p>
<p><b>Avg Sales:</b> {int(df['sales'].mean())}</p>
<p><b>Total Orders:</b> {len(df)}</p>
</div>

</div>
</div>
"""))

**ADD VISUAL INSIGH**

In [ ]:
import plotly.express as px

top_data = df.groupby('category')['sales'].sum().reset_index()

fig = px.bar(
    top_data.sort_values(by='sales', ascending=False).head(5),
    x='category',
    y='sales',
    title="Top 5 Categories",
)

fig.update_layout(template="plotly_dark")
fig.show()